Repository TUM-Dev/campus_flutter, pull requests merged in 2023-07, with the labels that each got.

#45 add settings view and permission checker
  ios/Runner/Info.plist
  lib/base/helpers/hyperlink_text.dart
  lib/base/helpers/padded_divider.dart
  lib/base/helpers/url_launcher.dart
  lib/departuresComponent/views/departures_details_row_view.dart
  lib/homeComponent/contactComponent/views/link_view.dart
  lib/homeComponent/widgetComponent/views/widget_frame_view.dart
  lib/loginComponent/views/confirm_view.dart
  lib/loginComponent/views/permission_check_view.dart
  lib/providers_get_it.dart
  lib/settingsComponent/views/settings_view.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#50 Ci cd updates
  .github/workflows/deploy_beta.yml
  .github/workflows/lint_test_build.yml
  android/Gemfile
  android/Gemfile.lock
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/fastlane/Appfile
  android/fastlane/Fastfile
  android/gradlew
  android/gradlew.bat
  ios/fastlane/Fastfile
  ios/fastlane/Matchfile
Labels: enhancement

#59 Additional documentation
  .github/CONTRIBUTING.md
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#63 change directory of web app to adjust to new domain
  .github/workflows/deploy_web.yml
Labels: enhancement

#69 fix local android build
  android/app/build.gradle
Labels: bug

#70 Bugfix Parsing
  android/fastlane/Fastfile
  lib/base/networking/protocols/main_api.dart
  lib/calendarComponent/model/calendar_event.dart
  lib/calendarComponent/model/calendar_event.g.dart
  lib/calendarComponent/services/calendar_service.dart
  lib/gradeComponent/model/average_grade.dart
  lib/gradeComponent/model/average_grade.g.dart
  lib/gradeComponent/model/grade.dart
  lib/gradeComponent/model/grade.g.dart
  lib/gradeComponent/services/grade_service.dart
  lib/gradeComponent/views/grades_view.dart
  lib/lectureComponent/model/lecture.dart
  lib/lectureComponent/model/lecture.g.dart
  lib/lectureComponent/model/lecture_details.dart
  lib/lectureComponent/model/lecture_details.g.dart
  lib/lectureComponent/services/lecture_service.dart
  lib/main.dart
  lib/profileComponent/model/profile.dart
  lib/profileComponent/model/profile.g.dart
  lib/profileComponent/model/tuition.dart
  lib/profileComponent/model/tuition.g.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#75 Make TUFilm Cards Clickable + Fix Android WebView
  lib/base/helpers/url_launcher.dart
  lib/movieComponent/views/homeWidget/movie_card_view.dart
  lib/settingsComponent/views/settings_view.dart
Labels: bug, enhancement

#76 Fix Settings on Web and iOS Deployment
  ios/fastlane/Fastfile
  ios/fastlane/Matchfile
  lib/settingsComponent/views/settings_view.dart
Labels: bug
